fastq_dir: "../raw_data/"

reference: "/fedgenhome/rotimi/databases/hg19.fa"

output_dir: "../results/30_06_2025_output"

bed: "../dependencies/bed/Aviseq_hg19edit.bed"

annova_dir: "/fedgenhome/rotimi/softwares/annovar"

db_dir: "/fedgenhome/rotimi/softwares/annovar/humandb"

java_dir: "/fedgenhome/rotimi/softwares/jdk-17.0.10+7/bin/java"

picard_path: "/fedgenhome/rotimi/softwares/picard.jar"

gatk_path: "/fedgenhome/rotimi/softwares/gatk-4.6.2.0/gatk"

bcftools: "/fedgenhome/rotimi/softwares/bcftools-1.21/bcftools"

samtools: "/fedgenhome/rotimi/softwares/samtools-1.3.1/samtools"

tabix: "/fedgenhome/rotimi/.local/bin/tabix"

bwa: "/fedgenhome/rotimi/spack/opt/spack/linux-ubuntu22.04-icelake/gcc-11.4.0/bwa-0.7.17-cwb7uec2ksg6vajwwcnusv4643ubsweq/bin/bwa"