include: "rules/common.smk"

import os

configfile: "config.yaml"

FASTQ_DIR = config["fastq_dir"]
REFERENCE = config["reference"]
OUTPUT_DIR = config["output_dir"]
VCF_DIR = config["output_dir"]
BED = config["bed"]
PICARD_PATH = config["picard_path"]
JAVA_PATH = config["java_dir"]
ANNOVAR_DIR = config["annova_dir"]
DB_DIR = config["db_dir"]
GATK_PATH = config["gatk_path"]
SAMTOOLS_PATH = config["samtools"]
BCFTOOLS_PATH = config["bcftools"]
TABIX_PATH = config["tabix"]
BWA_PATH = config["bwa"]




SAMPLES = discover_samples(FASTQ_DIR)

print(f"Discovered samples: {SAMPLES}")

def validate_paths():
    missing_files = []
    for sample in SAMPLES:
        r1 = get_r1(sample, FASTQ_DIR)
        r2 = get_r2(sample, FASTQ_DIR)
        if not os.path.exists(r1):
            missing_files.append(r1)
        if not os.path.exists(r2):
            missing_files.append(r2)
    if missing_files:
        raise FileNotFoundError(f"Missing FASTQ files:\n" + "\n".join(missing_files))

validate_paths()

rule all:
    """
    The purpose of the rule all in a Snakemake workflow is to define 
    the final target files that the entire workflow should produce when executed
    """
    input:
        [get_bai(sample, OUTPUT_DIR) for sample in SAMPLES],
        [get_gvcf(sample, VCF_DIR) for sample in SAMPLES],
        [get_vcf(sample, VCF_DIR) for sample in SAMPLES],
        [get_filtered_vcf(sample, VCF_DIR) for sample in SAMPLES],
        [get_normalized_vcf(sample, VCF_DIR) for sample in SAMPLES],
        [get_annovar_out_vcf(sample, VCF_DIR) for sample in SAMPLES],
        [get_annovar_out_txt(sample, VCF_DIR) for sample in SAMPLES]



rule bwa_index:
    input:
        REFERENCE
    output:
        f"{REFERENCE}.bwt"
    params:
        bwa = BWA_PATH
    shell:
        "{params.bwa} index {input}"

rule bwa_mem:
    input:
        ref = REFERENCE,
        r1 = lambda wildcards: get_r1(wildcards.sample, FASTQ_DIR),
        r2 = lambda wildcards: get_r2(wildcards.sample, FASTQ_DIR),
        idx = REFERENCE + ".bwt"
    output:
        temp(os.path.join(OUTPUT_DIR, "{sample}.sam"))
    params:
        bwa = BWA_PATH
    shell:
        "{params.bwa} mem -t 8 {input.ref} {input.r1} {input.r2} > {output}"


rule sam_to_bam:
    input:
        os.path.join(OUTPUT_DIR, "{sample}.sam")
    output:
        temp(os.path.join(OUTPUT_DIR, "{sample}.bam"))
    # threads: 8
    params:
        samtools = SAMTOOLS_PATH
    shell:
        "{params.samtools} view -@ {threads} -bS {input} > {output}"

rule sort_bam:
    input:
        os.path.join(OUTPUT_DIR, "{sample}.bam")
    output:
        get_bam("{sample}", OUTPUT_DIR)
    # threads: 8
    params:
        samtools = SAMTOOLS_PATH
    shell:
        "{params.samtools} sort -@ {threads} -o {output} {input}"

rule index_bam:  # to index the sorted read alignments so that we can quickly access reads by the genomic location they were mapped to
    input:
        lambda wildcards: get_bam(wildcards.sample, OUTPUT_DIR)
    output:
        get_bai("{sample}", OUTPUT_DIR)
    params:
        samtools = SAMTOOLS_PATH
    shell:
        "{params.samtools} index {input}"

rule add_read_groups:
    input:
        bam = lambda wildcards: get_bam(wildcards.sample, OUTPUT_DIR),
        bai = lambda wildcards: get_bai(wildcards.sample, OUTPUT_DIR),
    output:
        bam = temp(get_rg_bam("{sample}", OUTPUT_DIR)),
        bai = temp(get_rg_bai("{sample}", OUTPUT_DIR))
    params:
        picard = PICARD_PATH,
        samtools = SAMTOOLS_PATH,
        java = JAVA_PATH
    shell:
        """
        {params.java} -jar {params.picard} AddOrReplaceReadGroups \
            I={input.bam} \
            O={output.bam} \
            RGID=1 \
            RGLB=lib1 \
            RGPL=ILLUMINA \
            RGPU=unit1 \
            RGSM={wildcards.sample}
        
        {params.samtools} index {output.bam}
        """

rule variant_calling:
    input:
        bam = get_rg_bam("{sample}", OUTPUT_DIR),
        bai = get_rg_bai("{sample}", OUTPUT_DIR),
        bed = BED,
        ref = REFERENCE
    output:
        gvcf = get_gvcf("{sample}", VCF_DIR)
    params:
        gatk = GATK_PATH,
        mem = "-Xmx4G",
        java = JAVA_PATH
    # threads: 4
    shell:
        """
        {params.gatk} --java-options "{params.mem}" HaplotypeCaller \
            -R {input.ref} \
            -I {input.bam} \
            -L {input.bed} \
            -O {output.gvcf} \
            -ERC GVCF
        """

rule GenotypeVcf: # Genotype the GVCF files to produce a VCF file
    input:
        gvcf = lambda wildcards: get_gvcf(wildcards.sample, VCF_DIR),
    output:
        vcf_out = get_vcf("{sample}", VCF_DIR)
    params:
        gatk = GATK_PATH
    shell:
        """
        {params.gatk} GenotypeGVCFs \
            -R {REFERENCE} \
            -V {input.gvcf} \
            -O {output.vcf_out}
        """

rule quality_control_gatk:
    input:
        vcf = lambda wildcards: get_vcf(wildcards.sample, VCF_DIR)
    output:
        filtered_vcf = get_filtered_vcf("{sample}", VCF_DIR)
    params:
        gatk = GATK_PATH
    shell:
        """
        {params.gatk} VariantFiltration \
            -V {input.vcf} \
            -O {output.filtered_vcf} \
            --filter-expression "QD < 2.0 || FS > 60.0 || MQ < 40.0 || SOR > 3.0" \
            --filter-name "LowQuality"
        """

rule normalize_vcf:
    input:
        filtered_vcf = lambda wildcards: get_filtered_vcf(wildcards.sample, VCF_DIR)
    output:
        normalized_vcf = get_normalized_vcf("{sample}", VCF_DIR)
    params:
        bcftools = BCFTOOLS_PATH,
        tabix = TABIX_PATH
    shell:
        """
        {params.bcftools} norm -f \
        {REFERENCE} -m -both \
        {input.filtered_vcf} -Oz -o {output.normalized_vcf}
        {params.tabix} -p vcf {output.normalized_vcf}
        """

rule annovar_annotation:
    input:
        normalized_vcf = lambda wildcards: get_normalized_vcf(wildcards.sample, VCF_DIR)
    output:
        avinput = temp(os.path.join(VCF_DIR, "{sample}.avinput")),
        annotated_vcf_prefix = get_annovar_out_vcf("{sample}", VCF_DIR),
        annotated_txt_prefix = get_annovar_out_txt("{sample}", VCF_DIR)

    params:
        annovar_dir = ANNOVAR_DIR,
        db_dir = DB_DIR,
        annotated_prefix = get_annovar_out("{sample}", VCF_DIR)
    shell:
        """
        {params.annovar_dir}/convert2annovar.pl -format vcf4 {input.normalized_vcf} > {output.avinput}
        {params.annovar_dir}/table_annovar.pl {output.avinput} {params.db_dir} -buildver hg19 \
            -out {params.annotated_prefix} -remove -protocol refGene,dbnsfp35a,clinvar_20240917,avsnp151 \
            -operation g,f,f,f -nastring . -vcfinput
        """


"""
TO run the workflow, use the command:
snakemake --cores 1 --verbose --printshellcmds
This will execute the Snakemake workflow defined in this Snakefile, processing the samples as specified in the configuration file.
"""